# Makefile for "../../bin/gpiokey".
# Generated automatically by makemf with the command line:
# makemf -O ../../bin/gpiokey
# Do not edit this file!

TARGET = ../../bin/gpiokey
CC = gcc
CCFLAGS = -c -I$$HOME/include -O
LD = gcc
LDFLAGS =  -L$$HOME/lib
LIBS = -lm

LIBS += -lX11 -lXss -lXtst
CCFLAGS += -std=c99 -O3 -Wall -Wno-parentheses -Wno-char-subscripts

$(TARGET): gpio.o main.o x11.o
	$(LD) $(LDFLAGS) -o $(TARGET) *.o $(LIBS)
	strip $(TARGET)

gpio.o: gpio.c x11.h
	$(CC) $(CCFLAGS) gpio.c

main.o: main.c gpio.h x11.h
	$(CC) $(CCFLAGS) main.c

x11.o: x11.c x11.h
	$(CC) $(CCFLAGS) x11.c

clean:
	rm -f gpio.o
	rm -f main.o
	rm -f x11.o
